_file="$0"
alias aliases="vi $_file"
alias be="bundle exec"
alias br="bundle exec rspec"
alias cov="cov-tree"
alias gb="git branch"
alias gd="git diff"
alias gs="git status"
alias irc="screen -RD irc"
alias ls="ls -G1"
alias realias="source $_file"
alias scr="screen"
alias tm="treemap"
unsetopt correct_all
